# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:      petals 

# >> macros
# << macros
%define _binary_payload w2.xzdio
%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}

Summary:    Beautiful, brain-teasing puzzle for 1-4 players
Version:    2.0.2
Release:    1
Group:      Applications/Internet
License:    GPLv3
BuildArch:  noarch
URL:        https://thp.io/2013/petals/
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 1.1.0
Requires:   libsailfishapp-launcher

BuildRequires:  qt5-qttools-linguist
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  sailfish-svg2png

%description
In Petals, you have to find 3 flowers that belong together: The petal color, shape and count and the core color have to be either the same or pairwise different for all 3 flowers.

%if "%{?vendor}" == "chum"
PackageName: petals
Type: desktop-application
Categories:
 - Game
DeveloperName: Thomas Perl
Custom:
 - RepoType: github
 - Repo: https://github.com/poetaster/petals
Icon: https://raw.githubusercontent.com/poetaster/petals/master/icons/172x172/petals.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/petals/main/screen1.png
 - https://raw.githubusercontent.com/poetaster/petals/main/screen2.png
 - https://raw.githubusercontent.com/poetaster/petals/main/screen3.png
Url:
  Homepage: https://thp.io/2013/petals/
  Bugtracker: https://github.com/poetaster/petals/issues
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_datadir}/%{name}
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/applications/%{name}.desktop
%{_datadir}/%{name}/qml
# >> files
# << files
